# -*- coding: utf-8 -*-
"""NirjaraMore_202301100049_Ass02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlqGBbHDEQ6EEQbp-twmDx9KnLaeK8RK

# Google Colab Lab Assignment - Pretrained Model

**Course Name:** Deep Learning

**Lab Title:** Research Paper Implementation with Pre-trained Model (EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks)

**Student Name:** Nirjara More

**Student ID:** 202301100049

**Batch:** A1

**Group Members:** Nirjara, Sneha, Vaishnavi, Disha

## Reference Paper

**Title:** "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks"

**Authors:** Mingxing Tan and Quoc V. Le

---
## Paper Overview

The research paper introduces EfficientNet, a convolutional neural network architecture designed to improve image classification performance while maintaining computational efficiency.

Traditional CNN models increase performance by scaling:
- **Depth** (more layers)
- **Width** (more channels)
- **Resolution** (larger images)

However, this paper proposes a **compound scaling method**, which balances all three factors simultaneously for better results.

EfficientNet models are pre-trained on large datasets like ImageNet and can be reused for different tasks using transfer learning.

### What I Implemented

Applied the same transfer learning methodology using **MobileNetV2** (pre-trained on ImageNet) on the **Rice Leaf Disease Dataset** to classify 3 disease categories:
- Leaf Smut
- Bacterial Leaf Blight
- Brown Spot

---
## Task 1: Research Paper Selection and Dataset Preparation

**Instructions:**

1. Select a research paper that applies a pre-trained model (e.g., VGG, ResNet, EfficientNet, etc.).

2. Identify the dataset used in the research paper and obtain or create a similar dataset.
   - **Dataset:** Rice Leaf Disease Dataset
   - **Dataset Link:** (https://www.kaggle.com/datasets/vbookshelf/rice-leaf-diseases)
   - **Description:** Contains images of rice leaves categorized into 3 disease classes: Leaf Smut, Bacterial Leaf Blight, and Brown Spot.

3. Perform necessary preprocessing steps:
   - Resize images to model input dimensions (224x224).
   - Apply MobileNetV2 preprocessing function.

4. Split the dataset into training (80%) and validation (20%) sets.
"""

import zipfile

zip_path = "/content/RiceLeafDiseasesDataset.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/dataset")

print("Dataset Extracted Successfully")

import os

# Check top-level extracted folder
print("Top-level folders:", os.listdir("/content/dataset"))

# Check class folders
print("Classes:", os.listdir("/content/dataset/rice_leaf_diseases"))

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

DATASET_PATH = "/content/dataset/rice_leaf_diseases"
IMG_SIZE = 224
BATCH_SIZE = 32

# Apply MobileNetV2 preprocessing and 80/20 train-validation split
datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

# Training set (80%)
train_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

# Validation set (20%)
val_data = datagen.flow_from_directory(
    DATASET_PATH,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

print(f"Training samples  : {train_data.samples}")
print(f"Validation samples: {val_data.samples}")
print(f"Classes           : {train_data.class_indices}")

# ------------------------------------------------
# Visualization - Sample Images from Each Class
# ------------------------------------------------
import matplotlib.pyplot as plt
import numpy as np

# Get one batch of training images
sample_images, sample_labels = next(train_data)
class_names = list(train_data.class_indices.keys())

# --- Plot 1: Sample images from each class ---
plt.figure(figsize=(10, 4))
plt.suptitle("Sample Images from Each Class")

for i in range(min(5, len(sample_images))):
    plt.subplot(1, 5, i+1)
    # Denormalize for display (MobileNetV2 preprocessing scales to [-1, 1])
    img = (sample_images[i] + 1) / 2.0
    img = np.clip(img, 0, 1)
    plt.imshow(img)
    label_idx = np.argmax(sample_labels[i])
    plt.title(class_names[label_idx], fontsize=8)
    plt.axis('off')

plt.tight_layout()
plt.show()

# --- Plot 2: Original vs Preprocessed comparison ---
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import os

# Load a raw image directly (before preprocessing)
class_folder = os.path.join(DATASET_PATH, class_names[0])
img_file = os.listdir(class_folder)[0]
raw_img = load_img(os.path.join(class_folder, img_file), target_size=(224, 224))
raw_array = img_to_array(raw_img) / 255.0  # just scaled to [0,1]

# Preprocessed version (MobileNetV2)
preprocessed = preprocess_input(img_to_array(raw_img))
preprocessed_display = (preprocessed + 1) / 2.0  # scale back for display

plt.figure(figsize=(6, 3))
plt.suptitle("Original vs MobileNetV2 Preprocessed")

plt.subplot(1, 2, 1)
plt.imshow(raw_array)
plt.title("Original")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(np.clip(preprocessed_display, 0, 1))
plt.title("Preprocessed")
plt.axis('off')

plt.tight_layout()
plt.show()

"""---
## Task 2: Model Implementation and Fine-tuning

**Instructions:**

1. Implement the pre-trained model as described in the research paper.
2. Visualize feature maps of a few layers.
3. Freeze initial layers and fine-tune the top layers according to the paper's methodology.
4. Optimize hyperparameters such as:
   - Learning rate: `0.00001`
   - Batch size: `32`
   - Number of epochs: `8`
   - Optimizer: `Adam`
5. Document any modifications or enhancements made to improve performance.



"""

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

# Load MobileNetV2 pre-trained on ImageNet (without top classification layer)
base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224, 224, 3)
)

# Freeze all base model layers (feature extractor stays fixed)
for layer in base_model.layers:
    layer.trainable = False

print(f"Total base model layers (frozen): {len(base_model.layers)}")

# Add custom classification head on top
x = base_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation='relu')(x)
output = layers.Dense(train_data.num_classes, activation='softmax')(x)

model = models.Model(inputs=base_model.input, outputs=output)
model.summary()

import matplotlib.pyplot as plt
import numpy as np

# Select the first 4 convolutional layers for feature map visualization
conv_layers = [layer for layer in model.layers if 'conv' in layer.name][:4]
layer_outputs = [layer.output for layer in conv_layers]
feature_map_model = models.Model(inputs=model.input, outputs=layer_outputs)

# Get one sample image from training data
sample_batch, _ = next(train_data)
sample_img = sample_batch[0:1]  # shape: (1, 224, 224, 3)

# Predict feature maps
feature_maps = feature_map_model.predict(sample_img)

# Visualize first 8 channels of each selected layer
for idx, (fmap, layer) in enumerate(zip(feature_maps, conv_layers)):
    print(f"Layer '{layer.name}' - Feature map shape: {fmap.shape}")
    num_filters = min(8, fmap.shape[-1])
    fig, axes = plt.subplots(1, num_filters, figsize=(16, 3))
    for i, ax in enumerate(axes):
        ax.imshow(fmap[0, :, :, i], cmap='viridis')
        ax.axis('off')
    plt.suptitle(f'Feature Maps - Layer {idx+1}: {layer.name}')
    plt.tight_layout()
    plt.show()

from tensorflow.keras.optimizers import Adam

# Compile the model
model.compile(
    optimizer=Adam(learning_rate=0.00001),  # Low LR for fine-tuning
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=8
)

"""---
## Task 3: Model Evaluation and Performance Comparison

**Instructions:**

1. Evaluate the trained model using performance metrics:
   - Accuracy, Precision, Recall, F1-score, Confusion Matrix

2. Compare the results with those reported in the research paper.

3. Identify potential weaknesses and suggest improvements.

**Deliverables:**
- Performance metrics summary
- Graphs/plots showcasing model accuracy and loss trends
- Comparison with research paper results
- Discussion on model performance and areas for improvement

"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

# Accuracy plot
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Loss plot
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt

# Predict on validation set
pred = model.predict(val_data)
y_pred = np.argmax(pred, axis=1)
y_true = val_data.classes
class_names = list(val_data.class_indices.keys())

# Classification Report (Precision, Recall, F1-Score)
print("=== Classification Report ===")
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
print("=== Confusion Matrix ===")
print(cm)

# Visualize Confusion Matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(ax=ax, cmap='Blues')
plt.title('Confusion Matrix')
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""### Performance Summary

| Metric | Our Implementation (MobileNetV2) | EfficientNet Paper (ImageNet) |
|--------|----------------------------------|-------------------------------|
| Accuracy | ~46-53% (validation) | ~97%+ |
| Precision (macro avg) | 0.50 | Higher |
| Recall (macro avg) | 0.46 | Higher |
| F1-Score (macro avg) | 0.44 | Higher |

### Comparison with Research Paper
The original EfficientNet paper reports top accuracy on large-scale datasets (ImageNet). Our implementation uses a much smaller dataset (120 total images, 3 classes) which limits performance. However, the same core methodology was applied: pre-trained model + transfer learning + Adam optimizer.

The model achieved an accuracy of **46-53%** on the validation dataset. Performance varied across classes, with Brown Spot achieving higher recall than others.

### Limitations
- Small dataset (only 120 images) significantly limits model generalization.
- Classes have similar visual features, causing misclassification.
- Only 8 training epochs - insufficient for full convergence.

### Suggested Improvements
- Increase dataset size with more images per class.
- Apply stronger **data augmentation** (flips, rotations, brightness adjustments).
- **Unfreeze and fine-tune** the upper layers of the pre-trained base model.
- Train for more epochs (20-50).
- Use actual EfficientNet as described in the original paper.

---
## Conclusion and Result Visualization

This assignment successfully implemented the transfer learning methodology from the EfficientNet paper using MobileNetV2 on the Rice Leaf Disease Dataset. The model was trained using frozen base layers with a custom classification head, optimized with Adam - directly mirroring the paper's approach.

While the validation accuracy (~46%) is modest due to the small dataset, the implementation correctly demonstrates the paper's core concept: leveraging pre-trained ImageNet weights for a new classification task. With more data and fine-tuning, performance can be significantly improved.

---
## Declaration

I, Nirjara More, confirm that the work submitted in this assignment is my own and has been completed following academic integrity guidelines. The code is uploaded on my GitHub repository account, and the repository link is provided below:

**GitHub Repository Link:** [Insert GitHub Link]

**Signature:** Nirjara More
"""