# -*- coding: utf-8 -*-
"""XAI_Assignment_202301100049.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZZisxbOXGXyKiLinmNYUJt6t8D_mqjw

# Explainable AI (XAI) Techniques in Machine Learning

**Assignment:** Implementing Explainable AI Techniques in Machine Learning and CNN Models  
**Dataset:** Breast Cancer Wisconsin (Diagnostic)  
**Model:** Random Forest Classifier  
**XAI Methods:** SHAP (Global + Local) & LIME (Local)

**Name:** Nirjara More

**PRN:** 202301100049

**Batch:** AIML4

---

## Table of Contents
1. [Part 1 — Dataset Selection & Preprocessing](#part1)
2. [Part 2 — Model Implementation & Evaluation](#part2)
3. [Part 3 — XAI: SHAP (Global Explanations)](#part3)
4. [Part 3 — XAI: SHAP Force Plots (Local Explanations)](#part4)
5. [Part 3 — XAI: LIME (Local Explanations)](#part5)
6. [Part 4 — Visualization & Analysis](#part6)
7. [Part 5 — Summary & Conclusions](#part7)

---
## Install & Import Libraries
"""

# Install required libraries (run once)
import subprocess, sys
pkgs = ['shap', 'lime', 'scikit-learn', 'numpy', 'pandas', 'matplotlib', 'seaborn']
result = subprocess.run(
    [sys.executable, '-m', 'pip', 'install', '--quiet', '--break-system-packages'] + pkgs,
    capture_output=True)
if result.returncode != 0:
    # fallback without flag (e.g. virtual envs, Colab)
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '--quiet'] + pkgs)
print('Libraries ready.')

# ── Core ──────────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# ── scikit-learn ───────────────────────────────────────────────────────
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, f1_score, confusion_matrix,
                              classification_report, roc_auc_score, roc_curve)

# ── XAI ───────────────────────────────────────────────────────────────
import shap
from lime.lime_tabular import LimeTabularExplainer

# ── Plotting style ─────────────────────────────────────────────────────
sns.set_theme(style='whitegrid', palette='Set2', font_scale=1.1)
plt.rcParams.update({'figure.dpi': 120, 'figure.facecolor': 'white'})
shap.initjs()   # enable SHAP JavaScript visualisations

print('✅  All libraries imported successfully.')
print(f'   numpy  {np.__version__}  |  pandas {pd.__version__}  |  shap {shap.__version__}')

"""---
<a id='part1'></a>
##  Part 1 — Dataset Selection & Preprocessing

### 1.1 Dataset Description

We use the **Breast Cancer Wisconsin (Diagnostic)** dataset — a classic binary-classification benchmark:  

| Property | Detail |
|---|---|
| Samples | 569 |
| Features | 30 real-valued, computed from digitised FNA images |
| Target | Malignant (0) / Benign (1) |
| Class balance | ~37 % malignant, ~63 % benign |

Features describe characteristics of cell nuclei: *radius, texture, perimeter, area, smoothness, compactness, concavity, concave points, symmetry, fractal dimension* — each measured as mean, standard error, and worst value.
"""

# ── Load dataset ───────────────────────────────────────────────────────
data = load_breast_cancer()
X_raw = pd.DataFrame(data.data, columns=data.feature_names)
y     = pd.Series(data.target, name='target')

print('Shape :', X_raw.shape)
print('Classes:', dict(zip(data.target_names, np.bincount(y))))
X_raw.head(3)

# ── Basic statistics ───────────────────────────────────────────────────
X_raw.describe().round(3)

# ── Check for missing values ───────────────────────────────────────────
missing = X_raw.isnull().sum()
print('Missing values per feature:')
print(missing[missing > 0] if missing.any() else '✅  No missing values found.')

"""### 1.2 Exploratory Data Analysis (EDA)"""

# ── Class distribution ─────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

counts = y.value_counts()
labels = [data.target_names[i] for i in counts.index]

axes[0].bar(labels, counts.values, color=['#E74C3C', '#2ECC71'], edgecolor='black', linewidth=0.8)
axes[0].set_title('Class Distribution', fontweight='bold')
axes[0].set_ylabel('Count')
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 3, str(v), ha='center', fontweight='bold')

axes[1].pie(counts.values, labels=labels, autopct='%1.1f%%',
            colors=['#E74C3C','#2ECC71'], startangle=140,
            wedgeprops={'edgecolor':'white','linewidth':2})
axes[1].set_title('Class Proportion', fontweight='bold')

plt.suptitle('Breast Cancer Dataset — Class Distribution', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Feature distributions (top 10 mean features) ──────────────────────
mean_features = [c for c in X_raw.columns if 'mean' in c]

fig, axes = plt.subplots(2, 5, figsize=(18, 7))
axes = axes.flatten()

for i, feat in enumerate(mean_features):
    for cls, color, lbl in zip([0, 1], ['#E74C3C', '#2ECC71'],
                               data.target_names):
        axes[i].hist(X_raw.loc[y == cls, feat], bins=25, alpha=0.6,
                     color=color, label=lbl, edgecolor='none')
    axes[i].set_title(feat.replace(' ', '\n'), fontsize=9, fontweight='bold')
    axes[i].legend(fontsize=7)

plt.suptitle('Feature Distributions by Class (Mean Features)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Correlation heatmap (mean features) ───────────────────────────────
fig, ax = plt.subplots(figsize=(12, 9))
corr = X_raw[mean_features].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm',
            center=0, linewidths=0.5, ax=ax, annot_kws={'size': 8})
ax.set_title('Feature Correlation Matrix (Mean Features)', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""### 1.3 Preprocessing"""

# ── Train / test split (80 / 20, stratified) ──────────────────────────
X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X_raw, y, test_size=0.20, random_state=42, stratify=y)

# ── StandardScaler — zero mean, unit variance ─────────────────────────
scaler = StandardScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train_raw),
                        columns=data.feature_names)
X_test  = pd.DataFrame(scaler.transform(X_test_raw),
                        columns=data.feature_names)

print(f'Training set  : {X_train.shape[0]} samples')
print(f'Test set      : {X_test.shape[0]} samples')
print(f'Features      : {X_train.shape[1]}')
print('\nPreprocessing steps:')
print('  1. No missing values → no imputation needed')
print('  2. All features are numeric → no encoding needed')
print('  3. Stratified 80/20 train-test split')
print('  4. StandardScaler applied (fit on train, transform on test)')

"""---
<a id='part2'></a>
## Part 2 — Model Implementation & Evaluation

### 2.1 Model: Random Forest Classifier

**Random Forest** is an ensemble of decision trees that:
- Reduces over-fitting via bagging and feature sub-sampling
- Natively provides feature importance scores
- Works well with SHAP TreeExplainer (exact, efficient)
"""

# ── Train Random Forest ────────────────────────────────────────────────
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)
print('✅  Model trained.')
print('\nHyperparameters:')
for k, v in rf.get_params().items():
    print(f'  {k:30s}: {v}')

"""### 2.2 Evaluation Metrics"""

# ── Predictions ───────────────────────────────────────────────────────
y_pred      = rf.predict(X_test)
y_pred_prob = rf.predict_proba(X_test)[:, 1]

acc     = accuracy_score(y_test, y_pred)
f1      = f1_score(y_test, y_pred, average='weighted')
roc_auc = roc_auc_score(y_test, y_pred_prob)

# 5-fold cross-validation on full dataset
cv_scores = cross_val_score(rf, X_raw, y, cv=5, scoring='accuracy')

print('=' * 45)
print('         MODEL EVALUATION SUMMARY')
print('=' * 45)
print(f'  Test Accuracy     : {acc:.4f}  ({acc*100:.2f}%)')
print(f'  F1-Score (weighted): {f1:.4f}')
print(f'  ROC-AUC Score     : {roc_auc:.4f}')
print(f'  CV Accuracy (5-fold): {cv_scores.mean():.4f} ± {cv_scores.std():.4f}')
print('=' * 45)
print('\nClassification Report:\n')
print(classification_report(y_test, y_pred,
                             target_names=data.target_names))

# ── Confusion matrix & ROC curve ───────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=data.target_names,
            yticklabels=data.target_names,
            linewidths=1, linecolor='white', annot_kws={'size': 14})
axes[0].set_title('Confusion Matrix', fontsize=13, fontweight='bold')
axes[0].set_xlabel('Predicted Label')
axes[0].set_ylabel('True Label')

# ROC curve
fpr, tpr, _ = roc_curve(y_test, y_pred_prob)
axes[1].plot(fpr, tpr, color='#2980B9', lw=2,
             label=f'ROC curve (AUC = {roc_auc:.4f})')
axes[1].plot([0,1],[0,1],'--', color='grey', lw=1, label='Random classifier')
axes[1].fill_between(fpr, tpr, alpha=0.15, color='#2980B9')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].set_title('ROC Curve', fontsize=13, fontweight='bold')
axes[1].legend(loc='lower right')

plt.suptitle('Random Forest — Performance Metrics', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ── Cross-validation scores ────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(8, 4))
folds = [f'Fold {i+1}' for i in range(len(cv_scores))]
bars = ax.bar(folds, cv_scores, color=sns.color_palette('Set2', len(cv_scores)),
              edgecolor='black', linewidth=0.7)
ax.axhline(cv_scores.mean(), ls='--', color='red', lw=1.5,
           label=f'Mean = {cv_scores.mean():.4f}')
for bar, val in zip(bars, cv_scores):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
            f'{val:.4f}', ha='center', va='bottom', fontsize=9)
ax.set_ylim(0.90, 1.01)
ax.set_ylabel('Accuracy')
ax.set_title('5-Fold Cross-Validation Accuracy', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.show()

"""---
<a id='part3'></a>
## Part 3A — XAI: SHAP Global Explanations

**SHAP (SHapley Additive exPlanations)** assigns each feature a Shapley value — its average marginal contribution across all possible subsets of features.  

- **Global**: Summary plots show which features drive predictions across the whole dataset  
- **Local**: Force plots show why the model made a specific prediction  
- **TreeExplainer**: Exact SHAP values for tree-based models, computed efficiently
"""

# ── Compute SHAP values ────────────────────────────────────────────────
explainer_shap = shap.TreeExplainer(rf)
shap_values    = explainer_shap.shap_values(X_test)   # shape: (n, features, 2)

# For binary: use class-1 (benign) SHAP values
sv_class1 = shap_values[:, :, 1] if shap_values.ndim == 3 else shap_values[1]
print('SHAP values shape (class 1):', sv_class1.shape)
print('✅  SHAP values computed.')

"""### 3.1 SHAP Summary Plot (Beeswarm) — Global"""

plt.figure(figsize=(10, 8))
shap.summary_plot(
    sv_class1, X_test,
    feature_names=data.feature_names,
    show=False, plot_size=None
)
plt.title('SHAP Summary Plot — Global Feature Impact (Benign class)',
          fontsize=13, fontweight='bold', pad=15)
plt.tight_layout()
plt.show()

"""**Interpretation:** Each dot is one test sample. The x-axis shows the SHAP value (impact on model output). Colour encodes the actual feature value (red = high, blue = low). Features are ranked by mean absolute SHAP value (top = most important).

### 3.2 SHAP Bar Plot — Mean Absolute Feature Importance
"""

mean_abs_shap = np.abs(sv_class1).mean(axis=0)
shap_df = pd.DataFrame({'feature': data.feature_names,
                         'mean_abs_shap': mean_abs_shap})\
            .sort_values('mean_abs_shap', ascending=True)

fig, ax = plt.subplots(figsize=(9, 10))
colors  = sns.color_palette('viridis', len(shap_df))
bars    = ax.barh(shap_df['feature'], shap_df['mean_abs_shap'],
                  color=colors, edgecolor='white', linewidth=0.4)
for bar, val in zip(bars, shap_df['mean_abs_shap']):
    ax.text(val + 0.0005, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=7.5)
ax.set_xlabel('Mean |SHAP value|', fontsize=11)
ax.set_title('Global Feature Importance via SHAP\n(Mean Absolute SHAP Value)',
             fontsize=13, fontweight='bold')
ax.spines[['top','right']].set_visible(False)
plt.tight_layout()
plt.show()

"""### 3.3 Sklearn Feature Importance vs SHAP Comparison"""

# ── Top-15 features: sklearn MDI vs SHAP ──────────────────────────────
mdi_importance = rf.feature_importances_
compare_df = pd.DataFrame({
    'feature'  : data.feature_names,
    'MDI'      : mdi_importance,
    'SHAP'     : mean_abs_shap
}).sort_values('SHAP', ascending=False).head(15)

x = np.arange(len(compare_df))
w = 0.38
fig, ax = plt.subplots(figsize=(14, 5))
ax.bar(x - w/2, compare_df['MDI'],  width=w, label='Sklearn MDI',
       color='#3498DB', edgecolor='white')
ax.bar(x + w/2, compare_df['SHAP'], width=w, label='SHAP',
       color='#E67E22', edgecolor='white')
ax.set_xticks(x)
ax.set_xticklabels(compare_df['feature'], rotation=40, ha='right', fontsize=8.5)
ax.set_ylabel('Importance Score')
ax.set_title('Feature Importance: Sklearn MDI vs SHAP (Top 15)', fontweight='bold', fontsize=12)
ax.legend()
ax.spines[['top','right']].set_visible(False)
plt.tight_layout()
plt.show()

"""### 3.4 SHAP Dependence Plot — Top Feature"""

# Identify top SHAP feature
top_feat = data.feature_names[np.argmax(mean_abs_shap)]
print(f'Top SHAP feature: {top_feat}')

fig, ax = plt.subplots(figsize=(8, 5))
shap.dependence_plot(
    top_feat, sv_class1, X_test,
    feature_names=list(data.feature_names),
    ax=ax, show=False
)
ax.set_title(f'SHAP Dependence Plot — {top_feat}', fontweight='bold', fontsize=12)
plt.tight_layout()
plt.show()

"""---
<a id='part4'></a>
## Part 3B — XAI: SHAP Local Explanations (Force Plots)
"""

# ── Pick sample indices: 1 correctly predicted from each class ─────────
correct_mask = y_pred == y_test.values
malignant_idx = np.where((y_test.values == 0) & correct_mask)[0][0]
benign_idx    = np.where((y_test.values == 1) & correct_mask)[0][0]

print(f'Sample #{malignant_idx}: True=Malignant, Predicted={data.target_names[y_pred[malignant_idx]]}')
print(f'Sample #{benign_idx}   : True=Benign,    Predicted={data.target_names[y_pred[benign_idx]]}')

# ── Waterfall plot: Malignant sample ─────────────────────────────────
base_val = explainer_shap.expected_value
if isinstance(base_val, (list, np.ndarray)):
    base_val = base_val[1]

exp_mal = shap.Explanation(
    values         = sv_class1[malignant_idx],
    base_values    = base_val,
    data           = X_test.iloc[malignant_idx].values,
    feature_names  = list(data.feature_names)
)

plt.figure(figsize=(10, 6))
shap.waterfall_plot(exp_mal, max_display=12, show=False)
plt.title('SHAP Waterfall — Malignant Sample (Local Explanation)',
          fontweight='bold', fontsize=12)
plt.tight_layout()
plt.show()

# ── Waterfall plot: Benign sample ─────────────────────────────────────
exp_ben = shap.Explanation(
    values        = sv_class1[benign_idx],
    base_values   = base_val,
    data          = X_test.iloc[benign_idx].values,
    feature_names = list(data.feature_names)
)

plt.figure(figsize=(10, 6))
shap.waterfall_plot(exp_ben, max_display=12, show=False)
plt.title('SHAP Waterfall — Benign Sample (Local Explanation)',
          fontweight='bold', fontsize=12)
plt.tight_layout()
plt.show()

"""**Interpretation:** Red bars push the prediction toward *benign*, blue bars push toward *malignant*. The base value (E[f(x)]) is the model's average prediction; the waterfall shows how each feature nudges that baseline."""

# ── SHAP decision plot for multiple samples ────────────────────────────
sample_indices = list(range(0, min(30, len(X_test))))

plt.figure(figsize=(10, 8))
shap.decision_plot(
    base_val,
    sv_class1[sample_indices],
    X_test.iloc[sample_indices],
    feature_names=list(data.feature_names),
    show=False
)
plt.title('SHAP Decision Plot — First 30 Test Samples',
          fontweight='bold', fontsize=12)
plt.tight_layout()
plt.show()

"""---
<a id='part5'></a>
##  Part 3C — XAI: LIME Local Explanations

**LIME (Local Interpretable Model-Agnostic Explanations)** fits a simple, interpretable model (linear regression) locally around a specific prediction by:
1. Perturbing the input sample
2. Getting the black-box model's predictions on those perturbations
3. Weighting perturbations by proximity to the original sample
4. Fitting a weighted linear model — its coefficients are the local explanation
"""

# ── Create LIME explainer ──────────────────────────────────────────────
lime_explainer = LimeTabularExplainer(
    training_data  = X_train.values,
    feature_names  = list(data.feature_names),
    class_names    = list(data.target_names),
    mode           = 'classification',
    random_state   = 42
)
print('✅  LIME explainer created.')

# Helper: plot a LIME explanation as a horizontal bar chart
def plot_lime(explanation, sample_label, class_idx=1):
    exp_list = explanation.as_list(label=class_idx)
    features, weights = zip(*exp_list)
    colors = ['#2ECC71' if w > 0 else '#E74C3C' for w in weights]
    y_pos  = np.arange(len(features))

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.barh(y_pos, weights, color=colors, edgecolor='white', linewidth=0.5)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(features, fontsize=9)
    ax.axvline(0, color='black', linewidth=0.8)
    ax.set_xlabel('LIME Weight (positive → Benign)')
    ax.set_title(f'LIME Explanation — {sample_label}\n'
                 f'Prediction: {data.target_names[explanation.predict_proba.argmax()]} '
                 f'(p={explanation.predict_proba.max():.3f})',
                 fontweight='bold', fontsize=11)
    ax.spines[['top','right']].set_visible(False)
    plt.tight_layout()
    plt.show()

# ── LIME — Malignant sample ───────────────────────────────────────────
lime_exp_mal = lime_explainer.explain_instance(
    data_row       = X_test.iloc[malignant_idx].values,
    predict_fn     = rf.predict_proba,
    num_features   = 12,
    num_samples    = 3000,
    labels         = (0, 1)
)
plot_lime(lime_exp_mal, 'Malignant Sample', class_idx=1)

# ── LIME — Benign sample ──────────────────────────────────────────────
lime_exp_ben = lime_explainer.explain_instance(
    data_row       = X_test.iloc[benign_idx].values,
    predict_fn     = rf.predict_proba,
    num_features   = 12,
    num_samples    = 3000,
    labels         = (0, 1)
)
plot_lime(lime_exp_ben, 'Benign Sample', class_idx=1)

"""**Interpretation:** Green bars are features that pushed the model toward *benign*; red bars pushed toward *malignant*. The feature condition (e.g., `worst radius <= 14.5`) shows the local boundary LIME discovered."""

# ── LIME for 3 random samples — side-by-side comparison ───────────────
np.random.seed(0)
sample_idxs = np.random.choice(len(X_test), 3, replace=False)

fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=False)

for ax, idx in zip(axes, sample_idxs):
    exp = lime_explainer.explain_instance(
        X_test.iloc[idx].values, rf.predict_proba,
        num_features=8, num_samples=2000, labels=(0, 1))
    exp_list  = exp.as_list(label=1)
    feats, ws = zip(*exp_list)
    colors    = ['#2ECC71' if w > 0 else '#E74C3C' for w in ws]
    y_pos     = np.arange(len(feats))
    ax.barh(y_pos, ws, color=colors, edgecolor='white')
    ax.set_yticks(y_pos)
    ax.set_yticklabels(feats, fontsize=7.5)
    ax.axvline(0, color='black', lw=0.8)
    true_lbl = data.target_names[y_test.values[idx]]
    pred_lbl = data.target_names[exp.predict_proba.argmax()]
    ax.set_title(f'Sample {idx}\nTrue: {true_lbl} | Pred: {pred_lbl}',
                 fontsize=9, fontweight='bold')
    ax.spines[['top','right']].set_visible(False)

plt.suptitle('LIME — Local Explanations for 3 Random Test Samples',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

"""---
<a id='part6'></a>
## Part 4 — Comprehensive Visualisation & Analysis
"""

# ── SHAP violin / box plots ────────────────────────────────────────────
top10_feats = shap_df.sort_values('mean_abs_shap', ascending=False).head(10)['feature'].values
top10_idx   = [list(data.feature_names).index(f) for f in top10_feats]

sv_top10 = sv_class1[:, top10_idx]
plot_df  = pd.DataFrame(sv_top10, columns=top10_feats).melt(
               var_name='Feature', value_name='SHAP value')

fig, ax = plt.subplots(figsize=(12, 6))
sns.boxplot(data=plot_df, x='Feature', y='SHAP value', palette='Set3', ax=ax)
ax.axhline(0, ls='--', color='red', lw=1)
ax.set_xticklabels(ax.get_xticklabels(), rotation=35, ha='right', fontsize=9)
ax.set_title('SHAP Value Distribution — Top 10 Features (Benign class)',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

# ── SHAP vs actual feature values (top 6) ─────────────────────────────
top6_feats = top10_feats[:6]
top6_idx   = top10_idx[:6]

fig, axes = plt.subplots(2, 3, figsize=(14, 8))
axes = axes.flatten()

for i, (feat, fidx) in enumerate(zip(top6_feats, top6_idx)):
    feat_vals = X_test.iloc[:, fidx].values
    sv_vals   = sv_class1[:, fidx]
    sc = axes[i].scatter(feat_vals, sv_vals, c=y_test.values,
                          cmap='RdYlGn', alpha=0.65, edgecolors='none', s=40)
    axes[i].axhline(0, ls='--', color='grey', lw=0.8)
    axes[i].set_xlabel(feat, fontsize=8)
    axes[i].set_ylabel('SHAP value', fontsize=8)
    axes[i].set_title(feat, fontsize=9, fontweight='bold')

plt.colorbar(sc, ax=axes, label='Class (0=Malignant, 1=Benign)',
             orientation='vertical', fraction=0.02)
plt.suptitle('Feature Value vs SHAP Value (Top 6 Features)',
             fontsize=13, fontweight='bold')
plt.tight_layout(rect=[0,0,0.95,1])
plt.show()

# ── LIME top features frequency across test samples ────────────────────
from collections import Counter

feature_freq = Counter()
n_explain = min(50, len(X_test))

for i in range(n_explain):
    exp = lime_explainer.explain_instance(
        X_test.iloc[i].values, rf.predict_proba,
        num_features=8, num_samples=1000, labels=(1,))
    for feat_cond, _ in exp.as_list(label=1):
        # Extract base feature name from condition string
        base = feat_cond.split(' ')[0] if feat_cond.split(' ')[0] in data.feature_names \
               else feat_cond.split(' ')[-1]
        feature_freq[feat_cond] += 1

top_conditions = feature_freq.most_common(15)
conds, freqs   = zip(*top_conditions)

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(range(len(conds)), freqs,
        color=sns.color_palette('magma', len(conds)), edgecolor='white')
ax.set_yticks(range(len(conds)))
ax.set_yticklabels(conds, fontsize=8)
ax.set_xlabel('Frequency (out of 50 explanations)')
ax.set_title('Most Frequent LIME Feature Conditions (Top 15)',
             fontsize=12, fontweight='bold')
ax.spines[['top','right']].set_visible(False)
plt.tight_layout()
plt.show()

# ── SHAP interaction heatmap (top 8 vs top 8) ─────────────────────────
top8_feats = top10_feats[:8]
top8_idx   = top10_idx[:8]

sv_corr = pd.DataFrame(sv_class1[:, top8_idx], columns=top8_feats).corr()

fig, ax = plt.subplots(figsize=(9, 7))
sns.heatmap(sv_corr, annot=True, fmt='.2f', cmap='PiYG', center=0,
            linewidths=0.5, ax=ax, annot_kws={'size': 9})
ax.set_title('SHAP Value Correlation — Top 8 Features\n'
             '(Reveals feature interaction patterns)',
             fontsize=12, fontweight='bold')
plt.tight_layout()
plt.show()

"""---
<a id='part7'></a>
##  Part 5 — Summary, Insights & Limitations

### 5.1 Results Summary
"""

# ── Final summary dashboard ────────────────────────────────────────────
summary = {
    'Metric'                  : ['Test Accuracy', 'F1-Score (weighted)',
                                  'ROC-AUC', 'CV Accuracy (5-fold mean)', 'CV Std'],
    'Value'                   : [f'{acc:.4f}', f'{f1:.4f}',
                                  f'{roc_auc:.4f}', f'{cv_scores.mean():.4f}',
                                  f'{cv_scores.std():.4f}']
}
print(pd.DataFrame(summary).to_string(index=False))

print('\nTop 5 features by SHAP importance:')
top5 = shap_df.sort_values('mean_abs_shap', ascending=False).head(5)
for rank, (_, row) in enumerate(top5.iterrows(), 1):
    print(f'  {rank}. {row["feature"]:35s}  SHAP={row["mean_abs_shap"]:.5f}')

"""### 5.2 Key Insights

#### Model Performance
The Random Forest achieved **>97 % test accuracy** and **ROC-AUC > 0.99**, demonstrating excellent discriminative ability on this dataset. The low cross-validation standard deviation confirms stability across different data splits.

#### SHAP — Global Insights
- **`worst concave points`**, **`worst perimeter`**, and **`mean concave points`** consistently rank as the most influential features — aligning with domain knowledge that cell nucleus concavity and size are key indicators of malignancy.
- High feature values for these metrics push predictions toward *malignant*; low values push toward *benign*.
- Some features (e.g., `fractal dimension`) have near-zero mean SHAP values, suggesting the model learns to ignore them — these could be candidates for dimensionality reduction.

#### SHAP vs Sklearn MDI
- Both methods agree on the top features, but MDI tends to over-estimate high-cardinality features. SHAP provides a more reliable estimate because it accounts for feature interactions.

#### LIME — Local Insights
- For the malignant sample, LIME reveals that high `worst radius` and `worst concave points` values were the primary drivers toward a malignant prediction.
- For the benign sample, low `worst area` and `worst perimeter` values pushed the prediction toward benign.
- LIME frequency analysis confirms that `worst` suffix features (extreme values) dominate local explanations across many samples.

#### Potential Biases / Unexpected Behaviours
- High correlation among `radius`, `perimeter`, and `area` features (r > 0.97) introduces multicollinearity — SHAP handles this via Shapley value averaging, but LIME may attribute importance unevenly to correlated features.
- The dataset is relatively balanced (~37/63) — `class_weight='balanced'` was used to further mitigate any residual bias.

### 5.3 Limitations

| Limitation | Impact | Mitigation |
|---|---|---|
| LIME is stochastic | Explanations may vary slightly between runs | Fix `random_state`; increase `num_samples` |
| LIME uses linear proxy | May not capture non-linear local structure | Use SHAP as complementary method |
| SHAP assumes feature independence for some baselines | Slight inaccuracy with correlated features | TreeExplainer mitigates this for RF |
| Dataset is relatively small (569 samples) | Limited generalisation evidence | Use external validation datasets |
| No CNN / image tasks in this notebook | Assignment scope not fully covered | A separate CNN notebook with Grad-CAM on CIFAR-10 would be needed |

### 5.4 Conclusions

XAI techniques dramatically improve the **trustworthiness** and **debuggability** of ML models:
- **SHAP** provides theoretically-grounded, globally consistent feature attributions
- **LIME** offers fast, intuitive, instance-level explanations
- Together they build clinician/stakeholder confidence in medical ML systems
- XAI also surfaces potential **fairness issues** and **spurious correlations** that accuracy metrics alone would miss
"""

print('='*55)
print('  ✅  Explainable AI Assignment — Complete')
print('='*55)
print('Parts completed:')
print('  ✔  Part 1: Dataset selection & preprocessing')
print('  ✔  Part 2: Random Forest model + evaluation metrics')
print('  ✔  Part 3A: SHAP — Global (summary, bar, dependence)')
print('  ✔  Part 3B: SHAP — Local (waterfall, decision plots)')
print('  ✔  Part 3C: LIME — Local (2 samples + 3-way comparison)')
print('  ✔  Part 4: Additional visualisations & analysis')
print('  ✔  Part 5: Report — insights, biases, limitations')